# -*- coding: utf-8 -*-
"""IEEECS_Proj_Ria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bZ3hcdVrF528yU9jG0iOd6tf0KmoZwCI
"""

! pip install streamlit -q
! wget -q -O - ipv4.icanhazip.com
! streamlit run app.py & npx localtunnel --port 8501